import type { Lang } from '../language/languageEngine'

export type VisualFilterArt =
  | 'any'
  | 'sort-newest'
  | 'sort-low'
  | 'sort-high'
  | 'price-any'
  | 'price-low'
  | 'price-mid'
  | 'price-high'
  | 'general-properties'
  | 'general-rooms'
  | 'general-beds'
  | 'popular-parking'
  | 'popular-entire'
  | 'popular-old-city'
  | 'popular-near-me'
  | 'room-any'
  | 'room-single'
  | 'room-double'
  | 'room-suite'
  | 'room-studio'
  | 'room-family'
  | 'bed-single'
  | 'bed-double'
  | 'bed-queen'
  | 'bed-king'
  | 'bed-sofa'
  | 'property-apartment'
  | 'property-villa'
  | 'property-room'
  | 'property-heritage'
  | 'property-farm'
  | 'property-chalet'
  | 'property-land'
  | 'property-office'
  | 'property-shop'
  | 'property-project'
  | 'amenity-wifi'
  | 'amenity-fast-internet'
  | 'amenity-parking'
  | 'amenity-bathroom'
  | 'amenity-breakfast'
  | 'meal-lunch'
  | 'meal-dinner'
  | 'meal-buffet'
  | 'meal-all-inclusive'
  | 'meal-restaurant'
  | 'meal-no-kitchen'
  | 'meal-halal'
  | 'meal-plan'
  | 'meal-vegetarian'
  | 'meal-room-service'
  | 'hotel-star-5'
  | 'hotel-star-4'
  | 'hotel-star-3'
  | 'hotel-star-2'
  | 'hotel-star-1'
  | 'amenity-generator'
  | 'amenity-kitchen'
  | 'amenity-ac'
  | 'amenity-balcony'
  | 'amenity-pool'
  | 'amenity-heating'
  | 'amenity-tv'
  | 'amenity-garden'
  | 'amenity-elevator'
  | 'view-sea'
  | 'view-mountain'
  | 'outdoor-bbq'
  | 'access-crib'
  | 'access-pet'
  | 'access-wheelchair'
  | 'access-ramp'
  | 'access-parking'
  | 'access-bathroom'
  | 'access-wide-doorway'
  | 'access-hearing-loop'
  | 'access-visual-aid'
  | 'access-service-animal'
  | 'trust-verified'
  | 'trust-rating'
  | 'trust-fast'
  | 'trust-family'
  | 'trust-instant'
  | 'trust-featured'
  | 'payment-shamcash'
  | 'payment-card'
  | 'payment-local-wallet'
  | 'car-sedan'
  | 'car-suv'
  | 'car-pickup'
  | 'car-van'
  | 'car-luxury'
  | 'car-economy'
  | 'car-toyota'
  | 'car-hyundai'
  | 'car-kia'
  | 'car-mercedes'
  | 'car-bmw'
  | 'car-electric'
  | 'car-gas'
  | 'car-diesel'
  | 'car-hybrid'
  | 'car-manual'
  | 'car-automatic'
  | 'condition-new'
  | 'condition-used'
  | 'market-furniture'
  | 'market-electronics'
  | 'market-appliances'
  | 'market-services'
  | 'sr-ride-economy'
  | 'sr-ride-comfort'
  | 'sr-ride-premium'
  | 'sr-ride-family-van'
  | 'sr-ride-city'
  | 'sr-ride-airport'
  | 'sr-ride-intercity'
  | 'sr-ride-hourly'
  | 'sr-ride-instant'
  | 'sr-ride-ac'
  | 'sr-ride-wifi'
  | 'sr-ride-luggage'
  | 'sr-ride-child-seat'
  | 'sr-ride-family-friendly'

export type VisualFilterOption = {
  id: string
  label: Record<Lang, string>
  art: VisualFilterArt
  photoSrc?: string
  photoAlt?: Record<Lang, string>
  photoPosition?: string
}

export type VisualFilterGroup = {
  id: string
  title: Record<Lang, string>
  mode: 'single' | 'multi'
  options: VisualFilterOption[]
}

export type VisualFilterSelection = Record<string, string | string[]>
