import { useEffect, useState } from 'react'
import type { Lang } from '../../engines/language/languageEngine'
import { fetchAdminHostInsights, type PlatformAdminHostInsight } from '../../shared/api/platformApi'

type Props = {
  lang: Lang
}

const copy = {
  ar: {
    eyebrow: 'توصيات التسعير',
    title: 'توصيات التسعير للمضيفين',
    subtitle: 'كل توصية هنا حقيقية — مبنية على بيانات حجز فعلية وتم توليدها بواسطة الذكاء الاصطناعي بناءً على طلب المضيف.',
    admin: 'الإدارة',
    loading: 'جار التحميل...',
    error: 'تعذر تحميل التوصيات.',
    empty: 'لا توجد توصيات مولّدة بعد.',
    generated: 'إجمالي التوصيات',
    emailed: 'تم إرسالها بالبريد',
    read: 'تمت قراءتها',
    host: 'المضيف',
    listing: 'الإعلان',
    message: 'التوصية',
  },
  en: {
    eyebrow: 'Pricing insights',
    title: 'Host pricing insights',
    subtitle: 'Every recommendation here is real — built from real booking data and generated by AI at a host\'s request.',
    admin: 'Admin',
    loading: 'Loading...',
    error: 'Could not load insights.',
    empty: 'No insights generated yet.',
    generated: 'Total generated',
    emailed: 'Emailed',
    read: 'Read',
    host: 'Host',
    listing: 'Listing',
    message: 'Recommendation',
  },
}

export function AiBrainPage({ lang }: Props) {
  const isAr = lang === 'ar'
  const t = copy[lang]
  const [insights, setInsights] = useState<PlatformAdminHostInsight[]>([])
  const [totals, setTotals] = useState({ generated: 0, emailed: 0, read: 0 })
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [message, setMessage] = useState('')

  useEffect(() => {
    void load()
  }, [])

  async function load() {
    setStatus('loading')
    try {
      const response = await fetchAdminHostInsights()
      setInsights(response.insights)
      setTotals(response.totals)
      setStatus('ready')
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : t.error)
    }
  }

  return (
    <main className="ai-brain-page" dir={isAr ? 'rtl' : 'ltr'}>
      <header className="ai-brain-top">
        <div>
          <span>◉</span>
          <strong>{t.title}</strong>
          <small>{t.eyebrow}</small>
        </div>
        <p>{t.subtitle}</p>
        <button onClick={() => (window.location.hash = '/admin/review')}>{t.admin}</button>
      </header>

      {status === 'loading' && <p>{t.loading}</p>}
      {status === 'error' && <p className="ai-brain-alert">{message}</p>}

      {status === 'ready' && (
        <>
          <section className="ai-panel-previews">
            <PreviewPanel title={t.generated} value={String(totals.generated)} />
            <PreviewPanel title={t.emailed} value={String(totals.emailed)} />
            <PreviewPanel title={t.read} value={String(totals.read)} />
          </section>

          {insights.length === 0 ? (
            <p>{t.empty}</p>
          ) : (
            <section className="ai-improvements-column">
              {insights.map((insight) => (
                <article className="ai-improvement-card" key={insight.id}>
                  <div>
                    <strong>{insight.host?.displayName || t.host}</strong>
                    <small>{insight.listing?.titleAr || insight.listing?.titleEn || t.listing}</small>
                    <p>{isAr ? insight.messageAr : insight.messageEn || insight.messageAr}</p>
                  </div>
                </article>
              ))}
            </section>
          )}
        </>
      )}
    </main>
  )
}

function PreviewPanel({ title, value }: { title: string; value: string }) {
  return (
    <article>
      <h2>{title}</h2>
      <strong>{value}</strong>
    </article>
  )
}
