import { useEffect, useState } from 'react'
import type { CSSProperties } from 'react'
import type { Lang } from '../../engines/language/languageEngine'
import {
  fetchHostInsights,
  generateHostInsight,
  markHostInsightRead,
  type HostDashboardMode,
  type PlatformHostInsight,
} from '../../shared/api/platformApi'

type Props = {
  lang: Lang
  mode?: HostDashboardMode
}

const copy = {
  ar: {
    back: 'العودة للوحة الاستضافة',
    title: 'توصيات التسعير',
    subtitle: 'توصيات مبنية على بيانات حجوزاتك وتسعيرك الفعلية، تُنشأ بواسطة الذكاء الاصطناعي عند الطلب.',
    loading: 'جار التحميل...',
    error: 'تعذر تحميل التوصيات.',
    empty: 'لا توجد توصيات بعد.',
    generate: 'توليد توصية جديدة',
    generating: 'جار التوليد...',
    generatedNone: 'كل إعلاناتك تبدو جيدة الآن — لا توجد توصية جديدة.',
    unread: 'جديد',
    emailSent: 'تم إرسال بريد إلكتروني',
    emailFailed: 'تعذر إرسال البريد الإلكتروني',
  },
  en: {
    back: 'Back to host dashboard',
    title: 'Pricing insights',
    subtitle: 'Recommendations built from your real booking and pricing data, generated by AI on demand.',
    loading: 'Loading...',
    error: 'Could not load insights.',
    empty: 'No insights yet.',
    generate: 'Generate new insight',
    generating: 'Generating...',
    generatedNone: 'All your listings look fine right now — no new insight.',
    unread: 'New',
    emailSent: 'Emailed',
    emailFailed: 'Email failed',
  },
}

export function HostInsightsPanel({ lang, mode = 'host' }: Props) {
  const t = copy[lang]
  const isAr = lang === 'ar'
  const [insights, setInsights] = useState<PlatformHostInsight[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [message, setMessage] = useState('')
  const [generateState, setGenerateState] = useState<'idle' | 'generating' | 'error'>('idle')
  const [generateMessage, setGenerateMessage] = useState('')

  useEffect(() => {
    void load()
  }, [])

  async function load() {
    setStatus('loading')
    try {
      const response = await fetchHostInsights(mode)
      setInsights(response.insights)
      setStatus('ready')
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : t.error)
    }
  }

  async function onGenerate() {
    setGenerateState('generating')
    setGenerateMessage('')
    try {
      const response = await generateHostInsight(mode)
      if (response.generated === 0) setGenerateMessage(t.generatedNone)
      setGenerateState('idle')
      await load()
    } catch (error) {
      setGenerateState('error')
      setGenerateMessage(error instanceof Error ? error.message : t.error)
    }
  }

  async function onOpen(insight: PlatformHostInsight) {
    if (insight.readAt) return
    try {
      const updated = await markHostInsightRead(insight.id, mode)
      setInsights((current) => current.map((row) => (row.id === updated.id ? updated : row)))
    } catch {
      // best-effort — read state is a UI nicety, not worth surfacing a failure for
    }
  }

  return (
    <main dir={isAr ? 'rtl' : 'ltr'} style={styles.page}>
      <button style={styles.back} onClick={() => (window.location.hash = '/host')}>
        {t.back}
      </button>
      <section style={styles.hero}>
        <h1 style={styles.title}>{t.title}</h1>
        <p style={styles.body}>{t.subtitle}</p>
        <button style={styles.generateButton} disabled={generateState === 'generating'} onClick={onGenerate}>
          {generateState === 'generating' ? t.generating : t.generate}
        </button>
        {generateMessage && <p style={generateState === 'error' ? styles.alert : styles.body}>{generateMessage}</p>}
      </section>

      {status === 'loading' && <p style={styles.body}>{t.loading}</p>}
      {status === 'error' && <p style={styles.alert}>{message}</p>}
      {status === 'ready' && insights.length === 0 && <p style={styles.body}>{t.empty}</p>}

      {insights.map((insight) => (
        <article key={insight.id} style={styles.card} onClick={() => onOpen(insight)}>
          {!insight.readAt && <span style={styles.unreadBadge}>{t.unread}</span>}
          <p style={styles.body}>{isAr ? insight.messageAr : insight.messageEn || insight.messageAr}</p>
          <small style={styles.meta}>
            {new Date(insight.createdAt).toLocaleString(isAr ? 'ar-SY' : 'en-US')}
            {insight.emailSentAt ? ` · ${t.emailSent}` : insight.emailError ? ` · ${t.emailFailed}` : ''}
          </small>
        </article>
      ))}
    </main>
  )
}

const styles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', background: '#0a0a0f', color: '#fff', padding: '32px 16px 90px', display: 'grid', gap: 16, maxWidth: 900, margin: '0 auto' },
  back: { justifySelf: 'start', minHeight: 42, border: '1px solid #30384d', borderRadius: 8, background: '#111827', color: '#fff', padding: '0 14px', fontWeight: 900 },
  hero: { border: '1px solid #1e1e2a', borderRadius: 8, padding: 18, background: '#111118', display: 'grid', gap: 10 },
  title: { margin: 0, fontSize: 28 },
  body: { color: '#9aa6ba', margin: 0, lineHeight: 1.6 },
  alert: { border: '1px solid rgba(255,96,96,.45)', borderRadius: 8, background: 'rgba(255,96,96,.1)', color: '#ffd1d1', padding: 14 },
  generateButton: { justifySelf: 'start', minHeight: 44, border: 0, borderRadius: 8, background: '#d5a915', color: '#1a1300', padding: '0 18px', fontWeight: 950 },
  card: { position: 'relative', border: '1px solid #242735', borderRadius: 8, background: '#101016', padding: 16, display: 'grid', gap: 6, cursor: 'pointer' },
  unreadBadge: { position: 'absolute', top: 12, insetInlineEnd: 12, background: 'rgba(213,169,21,.16)', color: '#d5a915', borderRadius: 999, padding: '2px 10px', fontSize: 11, fontWeight: 900 },
  meta: { color: '#6c7488' },
}
