export const API_ENDPOINTS = [
  ['GET', '/api/health', 'public', 'Check API service and PostgreSQL connectivity.'],
  ['GET', '/api/contracts', 'public', 'Read the prototype endpoint and security contract registry.'],
  ['POST', '/api/auth/register', 'public', 'Create account with server-side password hashing and phone hashing.'],
  ['POST', '/api/auth/password-reset', 'public', 'Set a new password after a verified password-reset email code; revokes all sessions.'],
  ['POST', '/api/auth/login', 'public', 'Start a secure session after password verification.'],
  ['POST', '/api/auth/logout', 'user', 'Revoke the calling session server-side so its token stops working immediately.'],
  ['POST', '/api/auth/logout-all', 'user', 'Revoke every session for the account by bumping its security epoch.'],
  ['GET', '/api/auth/sessions', 'user', 'List the caller\'s own active sessions.'],
  ['PATCH', '/api/admin/users/:id/status', 'admin', 'Set an account ACTIVE/SUSPENDED/DELETED and revoke its live sessions.'],
  ['PATCH', '/api/admin/users/:id/roles', 'admin', 'Add or remove account roles and revoke its live sessions.'],
  ['GET', '/api/listings', 'public', 'Search approved listings by division, location, dates, price, and guest count.'],
  ['POST', '/api/listings', 'user', 'Create a draft listing owned by the authenticated seller or host.'],
  ['GET', '/api/listings/:id', 'public', 'Read an approved listing detail page with host and division metadata.'],
  ['PATCH', '/api/listings/:id/submit', 'user', 'Submit a listing for admin review.'],
  ['POST', '/api/bookings', 'user', 'Create a booking request and reserve the listing dates.'],
  ['GET', '/api/bookings/:id', 'user', 'Read a booking detail page for the guest, host, or admin.'],
  ['GET', '/api/bookings/quote', 'public', 'Quote a stay (nights, stay, cleaning, taxes, other fees, protection, total, commission, host share) and whether it is bookable.'],
  ['GET', '/api/bookings/:id/cancel-quote', 'user', 'Preview the refund the guest would get by cancelling now (rule, refund, retained, deadline).'],
  ['PATCH', '/api/bookings/:id/cancel', 'user', 'Let a guest cancel an unpaid, requested or confirmed booking; refund follows the 72h / protection cancellation rules.'],
  ['PATCH', '/api/bookings/:id/dispute', 'user', 'Let a guest dispute an eligible confirmed or completed booking.'],
  ['POST', '/api/payments/local-wallet-proof', 'user', 'Upload Syrian local wallet proof for admin approval.'],
  ['GET', '/api/payments/:id', 'user', 'Read a payment receipt for the payer, host, or admin.'],
  ['GET', '/api/wallet', 'user', 'Read wallet balance derived from server-side ledger entries.'],
  ['POST', '/api/wallet/gifts', 'user', 'Create a gift locked to a server-generated recipient phone hash.'],
  ['GET', '/api/wallet/gifts/:id', 'user', 'Read safe gift preview fields for a recipient claim link.'],
  ['POST', '/api/wallet/gifts/:id/claim', 'user', 'Claim a gift with persisted attempt locks and audit logging.'],
  ['GET', '/api/me/overview', 'user', 'Read the signed-in user dashboard overview.'],
  ['GET', '/api/me', 'user', 'Read the signed-in account (id, email, display name) with its LIVE roles, to refresh a stored session.'],
  ['POST', '/api/me/become-host', 'user', 'Add the HOST role to the signed-in account (one account for guest and host).'],
  ['GET', '/api/host/profile', 'user', 'Read the signed-in host profile (photo, about, languages, city).'],
  ['PUT', '/api/host/profile', 'user', 'Save the signed-in host profile text fields.'],
  ['PATCH', '/api/host/profile/photo', 'user', 'Upload or replace the host profile photo (private bucket, signed URL).'],
  ['GET', '/api/host-profiles/:userId', 'public', 'Read guest-facing host profile fields for a host.'],
  ['GET', '/api/host/verification', 'user', 'Read the signed-in host verification status (verified, pending activation code, expiry) and onboarding tracker (step 1-4, sent-back feedback).'],
  ['POST', '/api/host/activate', 'user', 'Redeem the admin-issued 6-digit host activation code (5 attempts per code).'],
  ['GET', '/api/host/overview', 'user', 'Read host listings, requests, and operating totals.'],
  ['PATCH', '/api/host/requests/:id', 'user', 'Confirm or cancel a request for a host-owned listing.'],
  ['GET', '/api/host/payout-method', 'user', 'Read the signed-in host payout method (country-configured types).'],
  ['PUT', '/api/host/payout-method', 'user', 'Save the signed-in host payout method.'],
  ['GET', '/api/host/payouts', 'user', 'Read withdrawable balance, pending requests, and payout request history.'],
  ['POST', '/api/host/payouts', 'user', 'Request a withdrawal of released earnings (no money moves until an admin marks it paid).'],
  ['PATCH', '/api/host/listings/:id/status', 'user', 'Pause or resume a host-owned listing.'],
  ['GET', '/api/driver/rides', 'user', 'Read assigned SR rides for the signed-in driver.'],
  ['GET', '/api/driver/rides/pending', 'user', 'Read unclaimed SR ride requests available to self-accept.'],
  ['PATCH', '/api/driver/rides/:id/status', 'user', 'Move an assigned SR ride through arriving, in-progress, completed, or cancelled.'],
  ['GET', '/api/admin/review-queue', 'admin', 'List pending sellers, listings, payments, gifts, and disputes.'],
  ['PATCH', '/api/admin/review-queue/:entityType/:entityId', 'admin', 'Approve or reject an entity and write an audit log. Approving an unverified host\'s stay auto-issues and emails the activation code; rejecting a listing stores feedback for the host.'],
  ['POST', '/api/admin/listings/:id/ai-review', 'admin', 'Re-run the advisory AI pre-check of a listing (background 202; ?wait=1 waits). Never changes the listing status.'],
  ['GET', '/api/admin/payout-requests', 'admin', 'List host withdrawal requests with host and payout method details.'],
  ['PATCH', '/api/admin/payout-requests/:id', 'admin', 'Mark a host withdrawal paid (external reference; wallet DEBIT) or reject it with a reason.'],
  ['GET', '/api/admin/hosts', 'admin', 'List hosts with verification status, listing count and latest activation code (filter unverified/verified/all).'],
  ['POST', '/api/admin/hosts/:userId/activation-code', 'admin', 'Issue a host activation code (returned once; optional email); retires earlier unused codes.'],
  ['GET', '/api/admin/refunds', 'admin', 'List refund requests (filter by status) for execution.'],
  ['GET', '/api/admin/audit-log', 'admin', 'Read the latest admin and workflow audit events.'],
  ['GET', '/api/admin/platform-metrics', 'admin', 'Read platform totals for status, dashboard, and admin operations.'],
  ['POST', '/api/sr/quote', 'user', 'Preview a distance-based SR fare for a pickup/dropoff/category combination.'],
  ['POST', '/api/sr/rides', 'user', 'Create SR ride request with pickup/dropoff locations.'],
  ['GET', '/api/sr/rides/:id', 'user', 'Read an SR ride detail for the requester, assigned driver, or admin.'],
  ['PATCH', '/api/sr/rides/:id/assign-driver', 'admin', 'Admin override to assign a specific driver to a ride.'],
  ['PATCH', '/api/sr/rides/:id/claim', 'user', 'Driver self-accepts a pending SR ride from the live queue.'],
].map(([method, path, auth, purpose]) => ({ method, path, auth, purpose }))

export const PLATFORM_SECURITY_RULES = [
  'Passwords are scrypt hashes on the server only.',
  'Session tokens are signed, expiring server-side credentials and never stored in localStorage.',
  'Every session has a server-side record; logout revokes it so the token stops working immediately.',
  'Suspended or deleted accounts cannot log in or use previously issued sessions.',
  'Removing a role revokes that account\'s live sessions, so privilege cannot outlive the role.',
  'Admin and support roles cannot be created through public self-registration.',
  'Public registration requires a unique email or phone and returns safe conflict errors.',
  'Phone numbers used for gifts are stored and matched through server-generated hashes.',
  'Listing, booking, payment, host, and driver actions enforce owner or role checks before mutation.',
  'Booking dates, wallet gift amounts, and SR ride fares are validated before records are created.',
  'Booking amount and currency come from the approved listing record, never from client-submitted totals.',
  'Guest cancellation protection is stored on the booking and changes refund/fee treatment through server-side ledger rules.',
  'Guest cancellation refunds follow server-side rules (72h cutoff / protection) snapshotted on the booking; the retained amount is split 12% commission / 88% host at admin finalization.',
  'Unpaid booking requests expire after the country payment window and stop blocking dates.',
  'Host withdrawals move no money until an admin records an external payment; the wallet DEBIT can never exceed released earnings.',
  'Payment proof uploads for bookings require the signed-in guest who owns that booking.',
  'Syrian wallet transaction references are required and checked server-side to prevent duplicate proof submission.',
  'Manual Syrian wallet proofs never settle automatically; admin approval is required before confirmation.',
  'Wallet balance is derived from PostgreSQL ledger entries plus transactional cached balance.',
  'Gift claim codes are signed per gift, and attempts plus claim status persist in PostgreSQL.',
  'SR driver assignment requires an active driver account and driver ride status transitions are ordered.',
  'Admin review decisions, host request decisions, driver status changes, and disputes write audit rows.',
  'Public listing endpoints expose only approved inventory; drafts and rejected listings stay private.',
  'Platform metrics and audit logs are restricted to admin/support review flows.',
]
